baseURL = 'https://osborngh.github.io/'
copyright = "© 2020 - 2023 vinci"
languageCode = 'en-us'
title = 'The Codex Arundel'
enableRobotsTXT = true
enableGitInfo = true

[params]
  defaultTheme = "dark"
  themeColor = "aqua"
  themeContrast = "hard"
  author = "Vinci"

  [params.logo]
    text = "vinci"
	url = "/"

  [params.prism]
    languages = [
	  "css",
	  "armasm",
	  "asm6502",
	  "bash",
	  "c",
	  "cpp",
	  "zig",
	  "wasm",
	  "vim",
	  "v",
	  "typescript",
	  "toml",
	  "yaml",
	  "sql",
	  "scala",
	  "rust",
	  "regex",
	  "r",
	  "python",
	  "nim",
	  "nasm",
	  "markdown",
	  "llvm",
	  "lua",
	  "makefile",
	  "haskell",
	  "go",
	  "docker",
	  "javascript",
	  "diff",
	]
	plugins = [
	  "normalize-whitespace",
	  "toolbar",
	  "copy-to-clipboard",
	  "line-numbers",
	  "command-line",
	  "diff-highlight",
	]

[menu]
  [[menu.main]]
    identifier = "blog"
	name = "Blog"
	url = "/blog"
	weight = 10
  [[menu.main]]
    identifier = "projects"
	name = "Projects"
	url = "/projects"
	weight = 20
  [[menu.main]]
    identifier = "about"
	name = "About"
	url = "/about"
	weight = 40

[languages]
  [languages.en]
    languageName = "English"
	weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
	  unsafe = true

[build]
  # The theme enables writeStats which is required for PurgeCSS
  _merge = "deep"

# This hopefully will be simpler in the future.
# See: https://github.com/schnerring/hugo-theme-gruvbox/issues/16
[module]
  [[module.imports]]
    path = "github.com/schnerring/hugo-theme-gruvbox"
  [[module.imports]]
    path = "github.com/schnerring/hugo-mod-json-resume"
    [[module.imports.mounts]]
      source = "data"
      target = "data"
    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"
    [[module.imports.mounts]]
      source = "assets/css/json-resume.css"
      target = "assets/css/critical/44-json-resume.css"
  [[module.mounts]]
    # required by hugo-mod-json-resume
    source = "node_modules/simple-icons/icons"
    target = "assets/simple-icons"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/prismjs"
    target = "assets/prismjs"
  [[module.mounts]]
    source = "node_modules/prism-themes/themes"
    target = "assets/prism-themes"
  [[module.mounts]]
    source = "node_modules/typeface-fira-code/files"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/typeface-roboto-slab/files"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/@tabler/icons/icons"
    target = "assets/tabler-icons"
